### ISSUE TITLE
Threshold selection

### ISSUE THREAD

**Issue by Forest216** [rrenaud/Gibberish-Detector#15]
Threshold selection only uses two very small datasets. Is this method too simple? Is there a more appropriate way to select the threshold?

**Comment by rrenaud** [comment]
You can add more held out data and plot a precision/recall curve so you can trade-off false positives and false negatives.

**Comment by Forest216** [comment]
> 您可以添加更多保留的数据并绘制精度/召回曲线，从而可以权衡假阳性和假阴性。

Thanks a lot. I will  try it.

**Comment by Forest216** [comment]
> You can add more held out data and plot a precision/recall curve so you can trade-off false positives and false negatives.

Thanks a lot.I will try it.
