### ISSUE TITLE
Licence missing

### ISSUE THREAD

**Issue by rtkrruvinskiy** [rrenaud/Gibberish-Detector#2]
Hi!

Is it possible to include a licence for this repository? Without a licence, it defaults to all rights reserved and cannot be incorporated into other software.

Thanks!

**Comment by rrenaud** [comment]
Sure, sounds good.  What license do you want?  You can send me a pull request with some kind of permissive MIT/BSD style license if you want.

**Comment by rtkrruvinskiy** [comment]
Done. Thanks for the quick response!
